image: node:latest

stages:
  - deploy

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

build_browser:
  stage: deploy
  only:
    - master
  script:
    - ls
    - npm i
    - npm install -g cordova ionic
    - ionic cordova platform rm browser
    - ionic cordova platform add browser
    - ionic cordova build browser
  artifacts:
    name: 
      Deploy-PrestaTech_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}
    paths:
      - platforms/browser/www/
