image: node:latest

stages:
  - build
  - test
  - deploy
cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

job:build_browser:
  stage: build
  only:
    - master
  script:
    - ls
    - npm i
    - npm install -g cordova ionic
    - ionic cordova platform rm browser
    - ionic cordova platform add browser
    - ionic cordova build browser
  artifacts:
    name: 
      Deploy-PrestaTech_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}
    paths:
      - platforms/browser/www/
 
job:test:unit:
  stage: test 
  script: make test-unit

job:test:functional:
  stage: test 
  script: make test-functional
  
job:deploy:
  stage: deploy 
  script: 
     - ls