image: node:latest

stages:
  - build
  - release

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/

build_browser:
  stage: build
  only:
    - master
  script:
    - ls
    - npm i
    - npm install -g cordova ionic
    - ionic cordova platform rm browser
    - ionic cordova platform add browser
    - ionic cordova build browser
  artifacts:
    name: 
      Deploy-PrestaTech_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}
    paths:
      - platforms/browser/www/
release:
  stage: release
  only: tags
  script:
    - make changelog | tee release_changelog.txt
  release:
    name: My $CI_PROJECT_NAME Release 1.0-$CI_COMMIT_SHORT_SHA
    description: ./release_changelog.txt
    assets:
    - name: cool-app.zip
      url: http://my.awesome.download.site/1.0-$CI_COMMIT_SHORT_SHA.zip
    - name: document-${APP_VERSION}.pdf
      path: out/doc/document.pdf
